-- Switch visual search from retired/mock 512-dimension providers to Replicate CLIP.
-- This clears existing vectors because older rows may have been generated by mock fallback code.
drop function if exists public.match_saree_images(vector(512), float, int);
drop function if exists public.match_saree_images(vector(768), float, int);

drop index if exists public.product_image_embeddings_cosine_idx;

truncate table public.product_image_embeddings;

alter table public.product_image_embeddings
  alter column embedding type vector(768);

create index if not exists product_image_embeddings_cosine_idx
  on public.product_image_embeddings
  using hnsw (embedding vector_cosine_ops);

create or replace function public.match_saree_images (
  query_embedding vector(768),
  match_threshold float,
  match_count int
)
returns table (
  id uuid,
  product_group_key text,
  variant_code text,
  image_url text,
  similarity float
)
language plpgsql
as $$
begin
  return query
  select
    pie.id,
    pie.product_group_key,
    pie.variant_code,
    pie.image_url,
    1 - (pie.embedding <=> query_embedding) as similarity
  from public.product_image_embeddings pie
  where 1 - (pie.embedding <=> query_embedding) > match_threshold
  order by pie.embedding <=> query_embedding
  limit match_count;
end;
$$;
